package recordManager;


/**
* recordManager/RecordManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from recordManager.idl
* Tuesday, June 19, 2018 10:40:45 PM EDT
*/

public interface RecordManager extends RecordManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RecordManager
