package recordManager;


/**
* recordManager/RecordManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from recordManager.idl
* Tuesday, June 19, 2018 10:40:45 PM EDT
*/

public interface RecordManagerOperations 
{
  String createTRecord (String managerID, String firstName, String lastName, String address, String phone, String specialization, String Location);
  String createSRecord (String managerID, String firstName, String lastName, String courseRegesitered, String status, String statusDate);
  String getCount (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String remoteServerName);
} // interface RecordManagerOperations
